=== DarkTl/PyTFall/game/schema/chars.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "additionalProperties": false,
  "properties": {
    "arena_willing": { "type": "string" },
    "attack_skills": {
      "additionalProperties": false,
      "properties": {
        "FistAttack": { "type": "number" }
      },
      "required": [ "FistAttack" ],
      "type": "object"
    },
    "basetraits": {
      "items": { "type": "string" },
      "type": "array",
      "maxItems": 2
    },
    "battle_skills": {
      "additionalProperties": false,
      "properties": {
        "Fist Attack": { "type": "number" },
        "Knife Attack": { "type": "number" }
      },
      "type": "object"
    },
    "blocked_traits": { "type": "array" },
    "breasts": {
        "enum": ["Abnormally Large Boobs", "Big Boobs", "Average Boobs", "Small Boobs"],
        "default": "Average Boobs"
    },
    "btraits": { "type": "array" },
    "color": { "type": "string" },
    "desc": { "type": "string" },
    "elements": {
      "items": { "type": "string" },
      "type": "array"
    },
    "full_race": { "type": "string" },
    "fullname": { "type": "string" },
    "gender": { "enum": ["female"], "default": "female" },
    "gold": { "type": "number", "default": 0 },
    "height": {
        "enum": ["tall", "short", "average"],
        "default": "average"
    },
    "id": { "type": "string" },
    "level": { "type": "number", "default": 1 },
    "location": { "type": "string" },
    "magic_skills": {
      "properties": {},
      "type": "object"
    },
    "name": { "type": "string" },
    "nickname": { "type": "string" },
    "occupation": { "type": "string" },
    "origin": { "type": "string" },
    "personality": { "type": "string", "default": "Deredere"},
    "race": { "type": "string" },
    "skills": {
      "additionalProperties": false,
      "properties": {
        "anal": { "type": "number" },
        "bartending": { "type": "number" },
        "cleaning": { "type": "number" },
        "dancing": { "type": "number" },
        "exploration": { "type": "number" },
        "management": { "type": "number" },
        "oral": { "type": "number" },
        "refinement": { "type": "number" },
        "service": { "type": "number" },
        "sex": { "type": "number" },
        "strip": { "type": "number" },
        "teaching": { "type": "number" },
        "vaginal": { "type": "number" },
        "waiting": { "type": "number" }
      },
      "type": "object"
    },
    "stats": {
      "additionalProperties": false,
      "properties": {
        "agility": { "type": "number" },
        "attack": { "type": "number" },
        "character": { "type": "number" },
        "charisma": { "type": "number" },
        "constitution": { "type": "number" },
        "defence": { "type": "number" },
        "evasion": { "type": "number" },
        "intelligence": { "type": "number" },
        "luck": { "type": "number" },
        "magic": { "type": "number" },
        "mp": { "type": "number" },
        "reputation": { "type": "number" }
      },
      "required": [
        "agility",
        "attack",
        "character",
        "charisma",
        "constitution",
        "defence",
        "intelligence",
        "magic",
        "luck"
      ],
      "type": "object"
    },
    "status": { "enum": ["free", "slave"] },
    "traits": {
      "items": { "type": "string" },
      "type": "array"
    },
    "what_color": { "type": "string" }
  },
  "required": [
    "blocked_traits",
    "gold",
    "id",
    "location",
    "magic_skills",
    "name",
    "origin",
    "race",
    "skills",
    "stats",
    "status",
    "traits",
    "desc"
  ],
  "type": "object"
}

=== DarkTl/PyTFall/game/content/npc/shopkeepers/data_hidden_village.json
[
    {
        "id": "Ren_hidden_village",
        "name": "Ren",
        "desc": "One of the kunoichi of the hidden village. She owns the ninja shop.",
        "origin": "Naruto",
        
		"race": "Human",
        "location": "city",
        "status": "free",
        "gold": 1500,

        "color": "red",
        "what_color": "orange",

        "stats": {
            "charisma": 50,
            "constitution": 30,
            "luck": 30,
            "character": 80,
            "intelligence": 40,
            "attack": 30,
            "magic": 65,
            "defence": 40,
            "agility": 30,
            "mp": 60
        },
        "skills": {

        },
        "btraits": [
            
        ],
        "blocked_traits": [
            
        ],
        "traits": [
            "Virgin",
            "Average Boobs",
            "Long Legs",
            "Slim",
            "Former Assassin",
            "Kuudere",
            "Human"
        ],
        "attack_skills": {
            "FistAttack": 1
        },
        "magic_skills": {
        }
    }
]
