=== DarkTl/PyTFall/game/schema/gifts.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "properties": {
    "cblock": {
      "type": "number"
    },
    "chance": {
      "type": "number"
    },
    "desc": {
      "type": "string"
    },
    "dismod": {
      "type": "number"
    },
    "icon": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "infinite": {
      "type": "boolean"
    },
    "locations": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "price": {
      "type": "number"
    },
    "slot": {
      "type": "string"
    },
    "traits": {
      "properties": {
        "Ane": {
          "type": "number"
        },
        "Bokukko": {
          "type": "number"
        },
        "Dandere": {
          "type": "number"
        },
        "Deredere": {
          "type": "number"
        },
        "Imouto": {
          "type": "number"
        },
        "Impersonal": {
          "type": "number"
        },
        "Kamidere": {
          "type": "number"
        },
        "Kuudere": {
          "type": "number"
        },
        "Tsundere": {
          "type": "number"
        },
        "Yandere": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "slot",
    "price",
    "locations",
    "dismod",
    "chance",
    "infinite",
    "icon",
    "cblock",
    "id",
    "desc"
  ],
  "type": "object"
}

=== DarkTl/PyTFall/game/content/db/gifts.json
[{
		"id": "Exotic Bouquet",
		"icon": "content/items/gift/eb.png",
		"desc": "This tastefully-arranged bouquet is comprised of many types of flowers that usually only grow in faraway lands. It's colorful, it's gorgeous, and it shows that you're willing to spend a lot of money to impress.",
		"price": 150,
		"slot": "gift",
		"chance": 65,
		"dismod": 15,
		"cblock": 5,
		"type": "flowers",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Tsundere": 5,
			"Yandere": -10,
			"Kuudere": -5,
			"Dandere": -5,
			"Impersonal": -5,
			"Ane": -10,
			"Imouto": 10,
			"Kamidere": 10,
			"Bokukko": 10,
			"Deredere": 10
		}
	}, {
		"id": "Bouquet of White Roses",
		"icon": "content/items/gift/bwr.png",
		"desc": "Not very romantic, but girls love flowers anyway.",
		"price": 200,
		"slot": "gift",
		"chance": 40,
		"dismod": 20,
		"cblock": 10,
		"type": "flowers",
		"infinite": false,
		"locations": ["General Store"]
	}, {
		"id": "Red Rose",
		"icon": "content/items/gift/rr.png",
		"desc": "A single red rose is worth a lot to a girl.",
		"price": 200,
		"slot": "gift",
		"chance": 25,
		"dismod": 20,
		"cblock": 10,
		"type": "flowers",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Yandere": 10,
			"Shy": -5,
			"Not Human": 5,
			"Frigid": -10,
			"Imouto": -10,
			"Alien": -10
		}
	}, {
		"id": "Wild Flowers",
		"icon": "content/items/gift/wf.png",
		"desc": "This fresh bouquet of colorful flowers picked outside the city is guaranteed to brighten any girl's mood. It might not be enough to prevent her from getting mad at you for boning her best friend, but you'll be a step closer to that lofty goal.",
		"price": 60,
		"slot": "gift",
		"chance": 85,
		"dismod": 10,
		"cblock": 10,
		"infinite": true,
		"type": "flowers",
		"locations": ["General Store", "Look around"],
		"traits": {
			"Ill-mannered": -10,
			"Impersonal": -15,
			"Kamidere": -25,
			"Elf": 5,
			"Monster": -5,
			"Furry": -5,
			"Alien": -20
		}
	}, {
		"id": "Blue Rose",
		"icon": "content/items/gift/blr.png",
		"desc": "A rare blue rose. These things do not exist in nature, being a product of genetic modifications.",
		"price": 350,
		"slot": "gift",
		"chance": 25,
		"dismod": 30,
		"cblock": 9,
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Alien": -10,
			"Elf": -5,
			"Artificial Body": 10,
			"Android": 10
		}
	},

	{
		"id": "Black Rose",
		"icon": "content/items/gift/br.png",
		"desc": "A gloomy, but rare and beautiful flower.",
		"price": 250,
		"slot": "gift",
		"chance": 15,
		"dismod": -35,
		"cblock": 8,
		"infinite": false,
		"type": "spooky",
		"locations": ["General Store"],
		"traits": {
			"Optimist": -20,
			"Pessimist": 70,
			"Impersonal": 60,
			"Alien": 50,
			"Elf": -10,
			"Undead": 10,
			"Demonic Creature": 50,
			"Divine Creature": -20
		}
	}, {
		"id": "Voodoo Doll",
		"icon": "content/items/gift/vd.png",
		"desc": "A great gift for those who have many enemies.",
		"price": 140,
		"slot": "gift",
		"chance": 40,
		"dismod": -20,
		"cblock": 8,
		"type": "spooky",
		"infinite": false,
		"locations": ["Witches Hut", "Look around"],
		"traits": {
			"Vicious": 50,
			"Virtuous": -40,
			"Curious": 25,
			"Demonic Creature": 25,
			"Coward": -20,
			"Sadist": 25,
			"Ill-mannered": 10
		}
	}, {
		"id": "Basilisk Eye",
		"icon": "content/items/gift/be.png",
		"desc": "Basilisk eyes become semiprecious stones after the creature dies.",
		"price": 140,
		"slot": "gift",
		"chance": 40,
		"dismod": -20,
		"cblock": 8,
		"type": "spooky",
		"infinite": false,
		"locations": ["Witches Hut", "Look around"],
		"traits": {
			"Vicious": 50,
			"Virtuous": -40,
			"Curious": 25,
			"Demonic Creature": 25,
			"Coward": -20,
			"Sadist": 25,
			"Ill-mannered": 10
		}
	}, {
		"id": "Skull Bracelet",
		"icon": "content/items/gift/skb.png",
		"desc": "A half spooky, half cute trinket.",
		"price": 5,
		"slot": "gift",
		"chance": 30,
		"dismod": -40,
		"cblock": 5,
		"type": "spooky",
		"infinite": false,
		"locations": ["Look around"],
		"traits": {
			"Undead": 50,
			"Demonic Creature": 50,
			"Pessimist": 45
		}
	}, {
		"id": "Pumpkin Candy",
		"icon": "content/items/gift/pc.png",
		"desc": "No, it doesn't taste like an evil pumpkin. Just looks like one.",
		"price": 5,
		"slot": "gift",
		"chance": 30,
		"dismod": -40,
		"cblock": 5,
		"type": "spooky",
		"infinite": false,
		"locations": ["Look around"],
		"traits": {
			"Undead": 50,
			"Demonic Creature": 50,
			"Pessimist": 45
		}
	},

	{
		"id": "Gold Pendant",
		"icon": "content/items/gift/gp.png",
		"desc": "A finely crafted heart pendant that hangs on a fine golden chain.",
		"price": 250,
		"slot": "gift",
		"chance": 45,
		"dismod": 30,
		"cblock": 10,
		"infinite": false,
		"type": "adornment",
		"locations": ["General Store"],
		"traits": {
			"Tsundere": 5,
			"Frigid": -15,
			"Yandere": 5,
			"Alien": -10,
			"Kleptomaniac": 5
		}
	}, {
		"id": "Emerald Ring",
		"desc": "Just don't forget to say that emerald suits her eyes or something.",
		"icon": "content/items/gift/er.png",
		"price": 600,
		"slot": "gift",
		"chance": 15,
		"dismod": 50,
		"cblock": 30,
		"type": "adornment",
		"infinite": false,
		"locations": ["General Store"]
	}, {
		"id": "Ruby Earrings",
		"icon": "content/items/gift/re.png",
		"desc": "A pair of expensive and beautiful earrings.",
		"price": 350,
		"slot": "gift",
		"chance": 30,
		"dismod": 20,
		"cblock": 30,
		"type": "adornment",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Ane": 15,
			"Bokukko": -25,
			"Kamidere": 25,
			"Kleptomaniac": 10
		}
	}, {
		"id": "Jewelry Brooch",
		"icon": "content/items/gift/jb.png",
		"desc": "An expensive and elegant brooch in the form of a butterfly.",
		"price": 650,
		"slot": "gift",
		"chance": 15,
		"dismod": 40,
		"cblock": 7,
		"type": "adornment",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Elf": 10
		}
	}, {
		"id": "Jewelry Hairpin",
		"icon": "content/items/gift/jh.png",
		"desc": "A tiny golden hairpin inlaid with small gems.",
		"price": 650,
		"slot": "gift",
		"chance": 15,
		"dismod": 40,
		"cblock": 7,
		"type": "adornment",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Elf": 10
		}
	},

	{
		"id": "Suntan Cream",
		"icon": "content/items/gift/sc.png",
		"desc": "Protects your skin from sun's harmful rays and provides an even tan.",
		"price": 85,
		"slot": "gift",
		"chance": 85,
		"dismod": 5,
		"cblock": 7,
		"infinite": true,
		"type": "cosmetics",
		"locations": ["General Shop"],
		"traits": {
			"Android": -25,
			"Athletic": 10,
			"Undead": 5,
			"Slime": -5
		}
	}, {
		"id": "Spa Set",
		"icon": "content/items/gift/ss.png",
		"desc": "Everything you need for a good long rest at the weekend.",
		"price": 150,
		"slot": "gift",
		"chance": 60,
		"dismod": 10,
		"cblock": 10,
		"type": "cosmetics",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Neat": 5,
			"Messy": -5,
			"Artificial Body": -5,
			"Alien": 5
		}
	}, {
		"id": "Fancy Soap",
		"icon": "content/items/gift/fs.png",
		"desc": "Aromatic soap with a slight tonic effect.",
		"price": 40,
		"slot": "gift",
		"chance": 85,
		"dismod": 5,
		"cblock": 9,
		"type": "cosmetics",
		"infinite": false,
		"locations": ["General Store"],
		"traits": {
			"Neat": 5,
			"Messy": -4
		}
	}, {
		"id": "Scented Oil",
		"icon": "content/items/gift/so.png",
		"desc": "A bottle of scented oil for skin care.",
		"price": 150,
		"slot": "gift",
		"chance": 50,
		"dismod": 20,
		"cblock": 5,
		"type": "cosmetics",
		"infinite": false,
		"locations": ["General Store", "Witches Hut"],
		"traits": {
			"Artificial Body": -10,
			"Android": -10,
			"Undead": -15,
			"Slime": -15
		}
	}, {
		"id": "Exotic Perfume",
		"icon": "content/items/gift/ep.png",
		"desc": "A decorated bottle of quality perfume for special cases.",
		"price": 150,
		"slot": "gift",
		"chance": 50,
		"dismod": 20,
		"cblock": 5,
		"type": "cosmetics",
		"infinite": false,
		"locations": ["General Store", "Witches Hut"],
		"traits": {
			"Artificial Body": -10,
			"Android": -10,
			"Undead": -15,
			"Slime": -15
		}
	},

	{
		"id": "Ocarina",
		"icon": "content/items/gift/o.png",
		"desc": "A simple yet elegant wind instrument.",
		"price": 45,
		"slot": "gift",
		"chance": 70,
		"dismod": 5,
		"cblock": 7,
		"infinite": false,
		"locations": ["Fishing"],
		"traits": {
			"Shy": 5,
			"Dandere": 5,
			"Kamidere": -5,
			"Not Human": 5
		}
	}, {
		"id": "Shell Wreath",
		"icon": "content/items/gift/sw.png",
		"desc": "A cheap, but pretty and unusual adornment.",
		"price": 4,
		"slot": "gift",
		"chance": 70,
		"dismod": 20,
		"cblock": 1,
		"infinite": false,
		"type": "trinket",
		"locations": ["Look around"],
		"traits": {
			"Serious": -6,
			"Deredere": 5,
			"Bokukko": 5,
			"Imouto": 5
		}
	}, {
		"id": "Keychain",
		"icon": "content/items/gift/k.png",
		"desc": "A colorful cheap bauble.",
		"price": 20,
		"slot": "gift",
		"chance": 95,
		"dismod": 2,
		"cblock": 7,
		"type": "trinket",
		"infinite": true,
		"locations": ["General Shop", "Look around"],
		"traits": {
			"Optimist": 3,
			"Imouto": 4,
			"Pessimist": -5,
			"Kleptomaniac": -5,
			"Human": 1
		}
	}, {
		"id": "Friendship Band",
		"icon": "content/items/gift/fba.png",
		"desc": "A bit too straightforward, but some people may like it.",
		"price": 30,
		"slot": "gift",
		"chance": 50,
		"dismod": -5,
		"cblock": 10,
		"type": "trinket",
		"infinite": false,
		"locations": ["General Store", "Look around"],
		"traits": {
			"Alien": 10,
			"Bokukko": 15,
			"Imouto": 15,
			"Kuudere": 15,
			"Dandere": 15
		}
	}, {
		"id": "Silver Bells",
		"icon": "content/items/gift/sb.png",
		"desc": "A pair of small silver bells. They ring melodiously with every movement.",
		"price": 140,
		"slot": "gift",
		"chance": 60,
		"dismod": 10,
		"cblock": 9,
		"type": "trinket",
		"infinite": false,
