=== DarkTl/PyTFall/game/schema/items.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "additionalProperties": false,
  "properties": {
    "add_be_spells": {
      "items": { "$ref": "#/definitions/magic" },
      "type": "array"
    },
    "addeffects": {
      "items": { "type": "string" },
      "type": "array"
    },
    "addtraits": {
      "items": { "type": "string" },
      "type": "array"
    },
    "attacks": {
      "items": { "type": "string" },
      "type": "array"
    },
    "badness": { "type": "number", "min": 0, "max": 100},
    "badtraits": { "type": "array" },
    "cblock": { "type": "number" },
    "ceffect": { "type": "string" },
    "ch_multiplier": { "type": "number" },
    "chance": { "type": "number" },
    "ctemp": { "type": "number" },
    "damage_multiplier": { "type": "number" },
    "defence_bonus": { "$ref": "#/definitions/defenceValue" },
    "defence_multiplier": { "$ref": "#/definitions/defenceValue" },
    "delivery_bonus": { "$ref": "#/definitions/defenceValue" },
    "delivery_multiplier": { "$ref": "#/definitions/defenceValue" },
    "desc": { "type": "string" },
    "dismod": { "type": "number" },
    "eqchance": { "type": "number" },
    "evasion_bonus": { "type": "number" },
    "goodrait": {
      "items": { "type": "string" },
      "type": "array"
    },
    "goodtraits": { "type": "array" },
    "hidden": { "type": "boolean" },
    "icon": { "type": "string" },
    "id": { "type": "string" },
    "infinite": { "type": "boolean" },
    "jump_to_label": { "type": "string" },
    "locations": {
      "items": { "$ref": "#/definitions/locations" },
      "type": "array"
    },
    "max": { "$ref": "#/definitions/statValue" },
    "mdestruct": { "type": "boolean" },
    "min": { "$ref": "#/definitions/statValue" },
    "mod": { "$ref": "#/definitions/statValue" },
    "mod_skills": {
      "allOf": [
        { "$ref": "#/definitions/skillObject" },
        { "$ref": "#/definitions/objectWithNumArrayOf5" }
      ]
    },
    "mreusable": { "type": "boolean" },
    "mtemp": { "type": "number" },
    "price": { "type": "number" },
    "removeeffects": {
      "items": { "type": "string" },
      "type": "array"
    },
    "removetraits": { "type": "array" },
    "sex": { "enum": ["male", "female", "unisex"] },
    "skillmax": { "type": "number" },
    "slot": { "enum": ["body", "wrist", "weapon", "smallweapon", "resources",
        "ring", "misc", "loot", "head", "feet", "consumable", "cape", "amulet"] },
    "statmax": { "type": "number" },
    "type": { "type": "string" }
  },
  "required": [
    "chance",
    "icon",
    "id",
    "price",
    "slot",
    "desc"
  ],
  "type": "object"
}

=== DarkTl/PyTFall/game/content/db/items_building_resources.json
[
    {
    "id": "Bricks",
    "desc": "Fired clay bricks.",
    "icon": "content/items/building_resources/bricks.png",
    "price": 25,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    },
    {
    "id": "Stone",
    "desc": "Stone blocks carved directly from a rock. Sturdy, but heavy and expensive.",
    "icon": "content/items/building_resources/stone.png",
    "price": 55,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop"]
    },
    {
    "id": "Green Marble",
    "desc": "Slabs of metamorphic rock commonly used for sculpture and as a building material.",
    "icon": "content/items/building_resources/marble.png",
    "price": 210,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop"]
    },
    {
    "id": "Glass",
    "desc": "Amorphous transparent solid, primary constituent of sand.",
    "icon": "content/items/building_resources/glass.png",
    "price": 45,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    },
    {
    "id": "Wood",
    "desc": "Fresh wooden beams from the local forest.",
    "icon": "content/items/building_resources/wood.png",
    "price": 25,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    },
    {
    "id": "Nails",
    "desc": "Pin-shaped steel nails.",
    "icon": "content/items/building_resources/nails.png",
    "price": 5,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    }
]

=== DarkTl/PyTFall/game/content/db/items_fish.json
[
    {
    "id": "Anchovy",
    "desc": "A small, common forage fish.",
    "icon": "content/items/fish/anchovy.png",
    "price": 3,
    "chance": 90,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Bowfin",
    "desc": "A silent and agile underwater predator.",
    "icon": "content/items/fish/bowfin.png",
    "price": 10,
    "chance": 30,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Catfish",
    "desc": "A bony fish which barbels resemble a cat's whiskers.",
    "icon": "content/items/fish/catfish.png",
    "price": 8,
    "chance": 70,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Elephantfish",
    "desc": "A big fish with an ability to generate weak electric fields that allow it to sense environment.",
    "icon": "content/items/fish/elephant.png",
    "price": 20,
    "chance": 20,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Flying Fish",
    "desc": "An exotic fish capable to make powerful leaps out of water into air to evade predators.",
    "icon": "content/items/fish/flying_fish.png",
    "price": 15,
    "chance": 40,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Koi Carp",
    "desc": "A widespread partially domesticated fish often used for decorative purposes.",
    "icon": "content/items/fish/carp.png",
    "price": 5,
    "chance": 80,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Sea Urchin",
    "desc": "A small, spiny, globular animal resembling a hedgehog.",
    "icon": "content/items/fish/urchin.png",
    "price": 12,
    "chance": 50,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Tuna",
    "desc": "A large and heavy fish with lots of tasty meat. The main target of professional fishermen.",
    "icon": "content/items/fish/tuna.png",
    "price": 100,
    "chance": 15,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Sea Bass",
    "desc": "An elongated fish with a large mouth.",
    "icon": "content/items/fish/sea_bass.png",
    "price": 15,
    "chance": 30,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Clownfish",
    "desc": "A small omnivorous fish with a very unusual appearance. Can be found in most aquariums.",
    "icon": "content/items/fish/ruby.png",
    "price": 30,
    "chance": 25,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    },
    {
    "id": "Abyssal Fish",
    "desc": "A deep-water fish capable of luminescence.",
    "icon": "content/items/fish/luminous.png",
    "price": 70,
    "chance": 15,
    "slot": "loot",
    "type": "fish",
    "locations": ["Fishing"]
    }
  ]

=== DarkTl/PyTFall/game/content/db/items_scrolls.json
[{
    "id": "Fire Scroll",
    "desc": "This scroll contains the arcane formula of Fire spell.",
    "icon": "content/items/scrolls/fire.png",
    "price": 50,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Fire"]
    },
    {
    "id": "Fira Scroll",
    "desc": "This scroll contains the arcane formula of Fira spell.",
    "icon": "content/items/scrolls/fira.png",
    "price": 100,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Fira"]
    },
    {
    "id": "Firaga Scroll",
    "desc": "This scroll contains the arcane formula of Firaga spell.",
    "icon": "content/items/scrolls/firaga.png",
    "price": 150,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Firaga"]
    },
    {
    "id": "Firaja Scroll",
    "desc": "This scroll contains the arcane formula of Firaja spell.",
    "icon": "content/items/scrolls/firaja.png",
    "price": 200,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Firaja"]
    },
    {
    "id": "Fireball Scroll",
    "desc": "This scroll contains the arcane formula of Fireball spell.",
    "icon": "content/items/scrolls/fireball.png",
    "price": 250,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Fireball"]
    },
    {
    "id": "Solar Flash",
    "desc": "This scroll contains the arcane formula of Solar Flash spell.",
    "icon": "content/items/scrolls/solar_flash.png",
    "price": 300,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Solar Flash"]
    },
    {
    "id": "Meteor",
    "desc": "This scroll contains the arcane formula of Meteor spell.",
    "icon": "content/items/scrolls/meteor.png",
    "price": 300,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Meteor"]
    },
    {
    "id": "Flame Vortex",
    "desc": "This scroll contains the arcane formula of Flame Vortex spell.",
    "icon": "content/items/scrolls/flame_vortex.png",
    "price": 350,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Flame Vortex"]
    },
    {
    "id": "Cataclysm",
    "desc": "This scroll contains the arcane formula of Cataclysm spell.",
    "icon": "content/items/scrolls/cataclysm.png",
    "price": 400,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Cataclysm"]
    },
    {
    "id": "Water Scroll",
    "desc": "This scroll contains the arcane formula of Water spell.",
    "icon": "content/items/scrolls/water.png",
    "price": 50,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Water"]
    },
    {
    "id": "Watera Scroll",
    "desc": "This scroll contains the arcane formula of Watera spell.",
    "icon": "content/items/scrolls/watera.png",
    "price": 100,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Watera"]
    },
    {
    "id": "Waterga Scroll",
    "desc": "This scroll contains the arcane formula of Waterga spell.",
    "icon": "content/items/scrolls/waterga.png",
    "price": 150,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Waterga"]
    },
    {
    "id": "Waterja Scroll",
    "desc": "This scroll contains the arcane formula of Waterja spell.",
    "icon": "content/items/scrolls/waterja.png",
    "price": 200,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Waterja"]
    },
    {
    "id": "Geyser Scroll",
    "desc": "This scroll contains the arcane formula of Geyser spell.",
    "icon": "content/items/scrolls/geyser.png",
    "price": 250,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Geyser"]
    },
    {
    "id": "Heavy Rain",
    "desc": "This scroll contains the arcane formula of Heavy Rain spell.",
    "icon": "content/items/scrolls/heavy_rain.png",
    "price": 300,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["Heavy Rain"]
    },
    {
    "id": "High Tide",
    "desc": "This scroll contains the arcane formula of High Tide spell.",
    "icon": "content/items/scrolls/high_tide.png",
    "price": 350,
    "sex": "unisex",
    "chance": 30,
    "badness": 80,
    "eqchance": 40,
    "hidden": false,
    "infinite": false,
    "slot": "consumable",
    "type": "scroll",
    "add_be_spells": ["High Tide"]
    }
  ]
