=== DarkTl/PyTFall/game/schema/new_npcs.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "properties": {
    "ab_traits": {
      "type": "array"
    },
    "attack_skills": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "base_race": {
      "type": "string"
    },
    "basetraits": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "blocked_traits": {
      "type": "array"
    },
    "color": {
      "type": "string"
    },
    "desc": {
      "type": "string"
    },
    "fullname": {
      "type": "string"
    },
    "gender": {
      "type": "string"
    },
    "gold": {
      "type": "number"
    },
    "id": {
      "type": "string"
    },
    "level": {
      "type": "number"
    },
    "location": {
      "type": "string"
    },
    "magic_skills": {
      "type": "array"
    },
    "name": {
      "type": "string"
    },
    "origin": {
      "type": "string"
    },
    "race": {
      "type": "string"
    },
    "skills": {
      "properties": {
        "cleaning": {
          "type": "number"
        },
        "exploration": {
          "type": "number"
        },
        "management": {
          "type": "number"
        },
        "teaching": {
          "type": "number"
        }
      },
      "required": [
        "teaching",
        "management",
        "exploration",
        "cleaning"
      ],
      "type": "object"
    },
    "stats": {
      "properties": {
        "agility": {
          "type": "number"
        },
        "attack": {
          "type": "number"
        },
        "character": {
          "type": "number"
        },
        "charisma": {
          "type": "number"
        },
        "constitution": {
          "type": "number"
        },
        "defence": {
          "type": "number"
        },
        "intelligence": {
          "type": "number"
        },
        "luck": {
          "type": "number"
        },
        "magic": {
          "type": "number"
        }
      },
      "required": [
        "agility",
        "defence",
        "magic",
        "constitution",
        "intelligence",
        "character",
        "attack",
        "charisma",
        "luck"
      ],
      "type": "object"
    },
    "status": {
      "type": "string"
    },
    "traits": {
      "type": "array"
    },
    "what_color": {
      "type": "string"
    }
  },
  "required": [
    "origin",
    "status",
    "stats",
    "name",
    "gold",
    "level",
    "gender",
    "ab_traits",
    "traits",
    "basetraits",
    "race",
    "magic_skills",
    "location",
    "blocked_traits",
    "base_race",
    "fullname",
    "attack_skills",
    "id",
    "desc"
  ],
  "type": "object"
}

=== DarkTl/PyTFall/game/content/npc/shopkeepers/data_aine.json
[
    {
        "id": "Aine",
        "name": "Aine",
        "fullname": "Aine McSpud",
        "desc": "A cute Leprechaun living in the park. She teaches Dark and Light magic",
        "origin": "PyTFall",
        
        "base_race": "Elf",
        "gender": "female",
        "race": "Leprechaun",
        "location": "city",
        "status": "free",
        "gold": 1000,
        
        "color": "green",
        "what_color": "azure",
        
        "level": 55,
        "basetraits": ["Mage"],
        
        "stats": {
            "charisma": 70,
            "constitution": 30,
            "luck": 85,
            "character": 75,
            "intelligence": 75,
            "attack": 10,
            "magic": 90,
            "defence": 35,
            "agility": 40
        },
        
        "skills": {
            "cleaning": 20,
            "management": 600,
            "teaching": 2000,
            "exploration": 1000
        },
        "blocked_traits": [
        
        ],
        "ab_traits": [
        
        ],
        
        "traits": [
            "Dark",
            "Light",
            "Average Boobs",
            "Dandere",
            "Slim"
        ],
        "attack_skills": [
            "Blunt Strike"
        ],
        "magic_skills": [
            "Holyda",
            "Holyja",
            "Star Light",
            "Darkga",
            "Darkja",
            "Black Hole"
        ]
    }
]
