=== DarkTl/PyTFall/game/schema/traits.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "additionalProperties": false,
  "definitions": {

    "stat": {
      "additionalProperties": false,
      "properties": {
        "agility": {},
        "attack": {},
        "character": {},
        "charisma": {},
        "constitution": {},
        "disposition": {},
        "defence": {},
        "health": {},
        "intelligence": {},
        "luck": {},
        "magic": {},
        "mp": {},
        "upkeep": {},
        "vitality": {}
      },
      "type": "object"
    },
    "skill": {
      "additionalProperties": false,
      "properties": {
        "anal": {},
        "bartending": {},
        "bdsm": {},
        "cleaning": {},
        "dancing": {},
        "exploration": {},
        "group": {},
        "management": {},
        "oral": {},
        "refinement": {},
        "service": {},
        "sex": {},
        "strip": {},
        "teaching": {},
        "vaginal": {},
        "waiting": {}
      },
      "type": "object"
    },
    "element": {
      "additionalProperties": false,
      "properties": {
        "air": {},
        "darkness": {},
        "earth": {},
        "electricity": {},
        "fire": {},
        "healing": {},
        "ice": {},
        "light": {},
        "physical": {},
        "poison": {},
        "water": {},
        "wind": {}
      },
      "type": "object"
    },
    "defence": {
      "additionalProperties": false,
      "properties": {
        "magic": {},
        "melee": {},
        "ranged": {},
        "status": {}
      },
      "type": "object"
    },

    "objectWithNumericType": {
      "type": "object",
      "properties": {},
      "additionalProperties": { "type": "number" }
    },
    "numericArrayOf3": {
      "type": "array",
      "minItems": 3,
      "maxItems": 3,
      "items": { "type": "number" }
    },
    "numericArrayOf2": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": { "type": "number" }
    },
    "objectWithNumArrayOf3": {
      "type": "object",
      "properties": {},
      "additionalProperties": { "$ref": "#/definitions/numericArrayOf3" }
    },
    "objectWithNumArrayOf2": {
      "type": "object",
      "properties": {},
      "additionalProperties": { "$ref": "#/definitions/numericArrayOf2" }
    },

    "statValue": {
      "allOf": [
        { "$ref": "#/definitions/stat" },
        { "$ref": "#/definitions/objectWithNumericType" }
      ],
      "type": "object"
    },
    "elementValue": {
      "allOf": [
        { "$ref": "#/definitions/element" },
        { "$ref": "#/definitions/objectWithNumericType" }
      ],
      "type": "object"
    },
    "defenceValue": {
      "allOf": [
        { "$ref": "#/definitions/defence" },
        { "$ref": "#/definitions/objectWithNumericType" }
      ],
      "type": "object"
    }
  },

  "properties": {
    "defence_bonus": {
      "allOf": [
        { "$ref": "#/definitions/defence" },
        { "$ref": "#/definitions/objectWithNumArrayOf3" }
      ]
    },
    "mod_skills": {
      "allOf": [
        { "$ref": "#/definitions/skill" },
        { "$ref": "#/definitions/objectWithNumArrayOf3" }
      ]
    },
    "mod_stats": {
      "allOf": [
        { "$ref": "#/definitions/stat" },
        { "$ref": "#/definitions/objectWithNumArrayOf3" }
      ]
    },

    "init_skills": {
      "allOf": [
        { "$ref": "#/definitions/skill" },
        { "$ref": "#/definitions/objectWithNumArrayOf2" }
      ]
    },
    "leveling_stats": {
      "allOf": [
        { "$ref": "#/definitions/stat" },
        { "$ref": "#/definitions/objectWithNumArrayOf2" }
      ]
    },

    "MC_only_trait": { "type": "boolean" },
    "basetrait": { "type": "boolean" },
    "blocks": {
      "items": { "type": "string" },
      "type": "array"
    },
    "body": { "type": "boolean" },
    "breasts": { "type": "boolean" },
    "ch_multiplier": { "type": "number" },
    "character_trait": { "type": "boolean" },
    "client": { "type": "boolean" },
    "damage_multiplier": { "type": "number" },

    "defence_multiplier": { "$ref": "#/definitions/defenceValue" },
    "delivery_multiplier": { "$ref": "#/definitions/defenceValue" },
    "desc": { "type": "string" },
    "effects": {
      "items": { "type": "string" },
      "type": "array"
    },
    "el_absorbs": { "$ref": "#/definitions/elementValue" },
    "el_damage": { "$ref": "#/definitions/elementValue" },
    "el_defence": { "$ref": "#/definitions/elementValue" },
    "elemental": { "type": "boolean" },
    "evasion_bonus": { "$ref": "#/definitions/numericArrayOf3" },
    "font_color": { "type": "string" },
    "higher_tiers": {
      "items": { "type": "string" },
      "type": "array"
    },
    "icon": { "type": "string" },
    "id": { "type": "string" },
    "init_lvlmax": { "$ref": "#/definitions/statValue" },
    "init_max": { "$ref": "#/definitions/statValue" },
    "init_mod": { "$ref": "#/definitions/statValue" },
    "max": { "$ref": "#/definitions/statValue" },
    "min": { "$ref": "#/definitions/statValue" },
    "mob_only": { "type": "boolean" },
    "mod": { "$ref": "#/definitions/statValue" },
    "mod_ap": { "type": "number" },
    "occupations": {
      "items": {
          "enum": ["SIW", "Server", "Warrior", "Caster", "Specialist"]
      },
      "type": "array"
    },
    "permanent": { "type": "boolean" },
    "personality": { "type": "boolean" },
    "race": { "type": "boolean" },
    "resist": {
      "items": {
          "enum": [ "air", "darkness", "earth", "electricity", "fire",
              "healing", "ice", "light", "physical", "poison", "water",
              "wind" ]
      },
      "type": "array"
    },
    "sexual": { "type": "boolean" },
    "trEffMax": { "type": "number" },
    "type": { "type": "string" },
    "virginity": { "type": "boolean" }
  },
  "required": [
    "id"
  ],
  "type": "object"
}

=== DarkTl/PyTFall/game/content/db/traits_races.json
[
    {
    "id": "Elf",
    "max": {"charisma": 10, "constitution": -10, "agility": 5},
    "type": "race",
    "icon": "content/races/elf.png",
    "el_damage": {"earth": 0.1},
    "race": true
    },
    {
    "id": "Undead",
    "max": {"charisma": -10, "constitution": 10},
    "type": "race",
    "icon": "content/races/undead.png",
    "el_damage": {"darkness": 0.1},
    "el_defence": {"healing": 0.5, "darkness": 0.5},
    "race": true
    },
    {
    "id": "Furry",
    "max": {"agility": 10, "intelligence": -10},
    "type": "race",
    "icon": "content/races/furry.png",
    "race": true
    },
    {
    "id": "Android",
    "max": {"charisma": -15, "constitution": 15, "agility": 5},
    "type": "race",
    "icon": "content/races/android.png",
    "el_damage": {"electricity": 0.1},
    "el_defence": {"healing": 0.5, "ice": 0.1, "air": 0.1, "darkness": 0.1, "light": 0.1},
    "race": true
    },
   {
    "id": "Divine Creature",
    "max": {"charisma": 10, "magic": 5, "constitution": -15},
    "type": "race",
    "icon": "content/races/angel.png",
    "el_damage": {"light": 0.1},
    "el_defence": {"light": 0.1},
    "race": true
    },
   {
    "id": "Demonic Creature",
    "max": {"charisma": -25, "magic": 10, "constitution": 15},
    "type": "race",
    "icon": "content/races/demon.png",
    "el_damage": {"fire": 0.1},
    "el_defence": {"fire": 0.1},
    "race": true
    },
   {
    "id": "Human",
    "max": {"constitution": 5},
    "type": "race",
    "icon": "content/races/human.png",
    "race": true
    },
   {
    "id": "Monster",
    "max": {"attack": 10, "charisma": -10, "defence": 10},
    "type": "race",
    "icon": "content/races/monster.png",
    "race": true
    },
   {
    "id": "Slime",
    "max": {"defence": 30, "charisma": -30},
    "type": "race",
    "icon": "content/races/slime.png",
    "el_damage": {"water": 0.1},
    "race": true
    },
   {
    "id": "Unknown",
    "max": {"constitution": 10},
    "type": "race",
    "icon": "content/races/unknown.png",
    "race": true
    }
]

=== DarkTl/PyTFall/game/content/db/traits_elements.json
[
    {
    "id": "Fire",
    "desc": "The wildest of all elements bringing a change that can never be undone. In a blink of an eye, it can turn any obstacle to dust leaving nothing but scorched earth in its path. In unskilled hands, it can be more dangerous to its wielders than to their enemies…",
    "icon": "content/gfx/interface/images/elements/fire.png",
    "elemental": true,
    "el_damage": {"fire": 0.5, "ice": -0.5},
    "el_defence": {"fire": 0.2, "wind": 0.3, "water": -0.6},
    "font_color": "orangered"
    },
    {
    "id": "Water",
    "desc": "The most mysterious among the elements. Hiding it twisted and destructive nature under the calm surface. Leaving behind only rumble and bodies as proof of it fatal capabilities. ",
    "icon": "content/gfx/interface/images/elements/water.png",
    "elemental": true,
    "el_damage": {"electricity": -0.5, "water": 0.5},
    "el_defence": {"water": 0.2, "fire": 0.3, "ice": -0.6},
    "font_color": "blue"
    },
    {
    "id": "Air",
    "desc": "The most agile of the elements. Utilizing its transparency and omnipresence to maximum. Being able to strike swiftly and undetected, in capable hands this element does not give opponents much time to defend themselves.",
    "icon": "content/gfx/interface/images/elements/air.png",
    "elemental": true,
    "el_damage": {"air": 0.5, "earth": -0.5},
    "el_defence": {"air": 0.2, "electricity": 0.3, "fire": -0.6},
    "font_color": "lightgreen"
    },
    {
    "id": "Earth",
    "desc": "The slowest and sturdiest among the elements. Known for sacrificing speed in exchange for overwhelming destructive power. Unlike other elements that leaves evidence of their devastating acts, earth is capable of literally burying the truth.",
    "icon": "content/gfx/interface/images/elements/earth.png",
    "elemental": true,
    "el_damage": {"earth": 0.5, "air": -0.5},
    "el_defence": {"earth": 0.2, "ice": 0.3, "electricity": -0.6},
    "font_color": "tan"
    },
    {
    "id": "Darkness",
    "desc": "One of the two elements born from men desires, thoughts and deeds. Fuelling itself from anger, impure thoughts and evil acts. Dwelling deep in everyone’s soul, patiently expanding, slowly consuming ones soul.",
    "icon": "content/gfx/interface/images/elements/darkness.png",
    "elemental": true,
    "el_damage": {"light": -0.5, "darkness": 0.5},
    "el_defence": {"light": -0.8, "darkness": 0.4, "water": 0.25, "earth": 0.25, "ice": 0.25},
    "font_color": "darkviolet"
    },
    {
    "id": "Light",
    "desc": "One of the two elements born from men desires, thoughts and deeds. light nests itself inside everyone souls. Gaining its force from good acts and pure thoughts.",
    "icon": "content/gfx/interface/images/elements/light.png",
    "elemental": true,
    "el_damage": {"light": 0.5, "darkness": -0.5},
    "el_defence": {"darkness": -0.8, "light": 0.3, "fire": 0.25, "air": 0.25, "electricity": 0.25},
    "font_color": "lightyellow"
    },
    {
    "id": "Electricity",
    "desc": "The most unstable and transient among the elements. Has control over magnetic and particle-based fields and beams that are deadly but cannot exist for a long time.",
    "icon": "content/gfx/interface/images/elements/electricity.png",
    "elemental": true,
    "el_damage": {"electricity": 0.5, "water": -0.5},
    "el_defence": {"electricity": 0.2, "earth": 0.3, "air": -0.6},
    "font_color": "yellow"
    },
    {
    "id": "Ice",
    "desc": "The most solid and unchangeable among the elements. Can absorbe energy from the environment, strengthening itself and creating ice formations out of nowhere.",
    "icon": "content/gfx/interface/images/elements/ice.png",
    "elemental": true,
    "el_damage": {"ice": 0.5, "fire": -0.5},
    "el_defence": {"ice": 0.2, "water": 0.3, "earth": -0.6},
    "font_color": "lightblue"
    },
    {
    "id": "Neutral",
    "desc": "Neutral alignment is the most popular option among warriors that do not rely on use of magic. It will ensure good degree of resistance from anything some silly mage may throw at its wielder. On other hand, this is possibly the worst choice for any magic user.",
    "icon": "content/gfx/interface/images/elements/neutral.png",
    "elemental": true,
    "el_damage": {"fire": -0.1, "water": -0.1, "earth": -0.1, "air": -0.1, "ice": -0.1, "electricity": -0.1, "darkness": -0.2, "light": -0.2},
    "el_defence": {"fire": -0.1, "water": -0.1, "earth": -0.1, "air": -0.1, "ice": -0.1, "electricity": -0.1, "darkness": -0.2, "light": -0.2}
    },
    {
    "id": "Fire Immunity",
    "desc": "No damage from Fire element.",
    "resist": ["fire"]
    },
    {
    "id": "Water Immunity",
    "desc": "No damage from Water element.",
    "resist": ["water"]
    },
    {
    "id": "Air Immunity",
    "desc": "No damage from Air element.",
    "icon": "content/gfx/interface/images/elements/air.png",
    "resist": ["air"]
    },
    {
    "id": "Earth Immunity",
    "desc": "No damage from Earth element.",
    "resist": ["earth"]
    },
    {
    "id": "Darkness Immunity",
    "desc": "No damage from Darkness element.",
    "resist": ["darkness"]
    },
    {
    "id": "Light Immunity",
    "desc": "No damage from Light element.",
    "resist": ["light"]
    },
    {
    "id": "Electricity Immunity",
    "desc": "No damage from Electricity element.",
    "resist": ["electricity"]
    },
    {
    "id": "Ice Immunity",
    "desc": "No damage from Ice element.",
    "resist": ["ice"]
    },
    {
    "id": "Magic Immunity",
    "desc": "No damage from any magic.",
    "resist": ["ice", "Water", "Fire", "Air", "Earth", "Electricity", "Light", "Darkness", "Healing"]
    },
    {
    "id": "Fire Absorption",
    "desc": "Fire element restores health.",
    "el_absorbs": {"fire": 0.3}
    },
    {
    "id": "Water Absorption",
    "desc": "Water element restores health.",
    "el_absorbs": {"water": 0.3}
    },
    {
    "id": "Air Absorption",
    "desc": "Air element restores health.",
    "el_absorbs": {"air": 0.3}
    },
    {
    "id": "Earth Absorption",
    "desc": "Earth element restores health.",
    "el_absorbs": {"earth": 0.3}
    },
    {
    "id": "Darkness Absorption",
    "desc": "Darkness element restores health.",
    "el_absorbs": {"darkness": 0.3}
    },
    {
    "id": "Light Absorption",
    "desc": "Light element restores health.",
    "el_absorbs": {"light": 0.3}
    },
    {
    "id": "Electricity Absorption",
    "desc": "Electricity element restores health.",
    "el_absorbs": {"electricity": 0.3}
    },
    {
    "id": "Ice Absorption",
    "desc": "Ice element restores health.",
    "el_absorbs": {"ice": 0.3}
    }
    ]

=== DarkTl/PyTFall/game/content/db/traits_body.json
[
    {
    "id": "Abnormally Large Boobs",
    "desc": "One wonders how she keeps her balance. Those things are like miniature moons...",
    "blocks": ["Big Boobs", "Average Boobs", "Small Boobs"],
    "min": {"charisma": 10},
    "max": {"charisma": 20, "agility": -10},
    "mod_stats": {"charisma": [1, 1], "agility": [-1, 1]},
    "mod_skills": {"strip": [-0.1, 0, 0.2], "dancing": [-0.1, 0, -0.1]},
    "evasion_bonus": [-10, -10, 1],
    "breasts": true
    },
    {
    "id": "Big Boobs",
    "desc": "This girl really has knockers.",
    "blocks": ["Abnormally Large Boobs", "Average Boobs", "Small Boobs"],
    "min": {"charisma": 5},
    "max": {"charisma": 10, "agility": -5},
    "mod_stats": {"charisma": [1, 2], "agility": [-1, 2]},
    "mod_skills": {"strip": [-0.05, 0, 0.1]},
    "evasion_bonus": [-5, -5, 1],
    "breasts": true
    },
    {
    "id": "Average Boobs",
    "desc": "Her boobs are somewhere in the B-C cup range. Any classy guy will say that this is the ideal size.",
    "blocks": ["Abnormally Large Boobs", "Big Boobs", "Small Boobs"],
    "mod_stats": {"charisma": [1, 4]},
    "breasts": true
    },
    {
    "id": "Small Boobs",
    "desc": "Her boobs may be small, but some people like that.",
    "blocks": ["Abnormally Large Boobs", "Average Boobs", "Big Boobs"],
    "min": {"agility": 5},
    "max": {"charisma": -20, "agility": 10},
    "mod_stats": {"charisma": [-2, 2], "agility": [1, 2]},
    "mod_skills": {"strip": [-0.2, 0, -0.1], "dancing": [0.05, 0, 0.05]},
    "breasts": true,
    "evasion_bonus": [5, 5, 1]
    },
    {
    "id": "Not Human",
    "desc": "This girl doesn't look like a normal human being.",
    "mod": {"upkeep": 10},
    "mod_skills": {"strip": [0, 0, 0.03], "refinement": [-0.03, -0.03, 0.03]},
    "permanent": true
    },
   {
    "id": "Long Legs",
    "desc": "The legs on this girl go all the way to heaven.",
    "max": {"charisma": 5},
    "mod_stats": {"charisma": [1, 5], "agility": [1, 5]},
    "mod_skills": {"strip": [0, 0, 0.02], "dancing": [0, 0, 0.01]},
    "permanent": true
    },
   {
    "id": "Great Arse",
    "desc": "She has a really nice arse.",
    "max": {"charisma": 5},
    "mod_skills": {"strip": [0, 0, 0.02], "anal": [0.01, 0, 0.01]},
    "permanent": true
    },
   {
    "id": "Strange Eyes",
    "desc": "Her eyes are unusual in some way.",
    "mod_stats": {"charisma": [-2, 4]},
    "max": {"charisma": 10},
    "mod_skills": {"refinement": [0, 0, 0.01]},
    "permanent": true
    },
    {
    "id": "Lolita",
    "desc": "This girl looks very young and small.",
    "blocks": ["Slim", "Chubby", "Athletic", "Manly"],
    "min": {"agility": 5},
    "max": {"vitality": -100, "health": -50},
    "mod_stats": {"constitution": [-3, 1], "agility": [2, 2]},
    "mod_ap": 1,
    "body": true,
    "evasion_bonus": [5, 5, 1]
    },
    {
    "id": "Slim",
    "desc": "This girl has a slender, slim figure.",
    "blocks": ["Lolita", "Chubby", "Athletic", "Manly"],
    "mod_stats": {"constitution": [-1, 1], "charisma": [1, 1]},
    "max": {"vitality": -50},
    "body": true,
    "evasion_bonus": [1, 1, 1]
    },
    {
    "id": "Chubby",
    "blocks": ["Lolita", "Slim", "Athletic", "Manly"],
    "desc": "This girl has plump, slightly round figure.",
    "mod_stats": {"constitution": [1, 2], "agility": [-2, 1]},
    "max": {"health": 50},
    "body": true,
    "evasion_bonus": [-5, -5, 1]
    },
    {
    "id": "Athletic",
    "blocks": ["Lolita", "Slim", "Chubby", "Manly"],
    "desc": "This girl is tough and has trained a lot. Her body is in great shape.",
    "min": {"constitution": 5},
    "mod_stats": {"constitution": [1, 2], "agility": [1, 2]},
    "max": {"health": 25, "vitality": 50},
    "body": true,
    "evasion_bonus": [3, 3, 1]
    },
   {
    "id": "Manly",
    "blocks": ["Lolita", "Slim", "Chubby", "Athletic"],
    "desc": "This girl is very muscular. Perhaps even too muscular.",
    "min": {"constitution": 15},
    "mod_stats": {"constitution": [1, 2], "charisma": [-3, 1], "agility": [-3, 2]},
    "max": {"health": 25, "vitality": 100, "charisma": -50, "attack": 10, "defence": 10, "agility": -25},
    "mod_skills": {"service": [-0.02, 0, -0.03], "strip": [0, 0, -0.06], "waiting": [-0.01, 0, -0.02]},
    "body": true,
    "evasion_bonus": [-5, -5, 1]
    },
    {
    "id": "Artificial Body",
    "desc": "This girl's body is not alive or real, it is a machine or has been created with magic.",
    "mod": {"upkeep": 15},
    "min": {"constitution": 5, "defence": 15},
    "max": {"constitution": 10, "defence": 15, "health": 50, "vitality": 50},
    "permanent": true,
    "client": true,
    "el_defence": {"healing": 0.3, "poison": 0.35},
    "defence_bonus": {"melee":[20, 80, 50], "ranged":[15, 60, 50]}
    },
    {
    "id": "Scars",
    "desc": "This poor girl has some scars.",
    "mod": {"upkeep": 5},
    "mod_stats": {"constitution": [1, 2]},
    "max": {"charisma": -5},
    "mod_skills": {"strip": [0, 0, -0.1]},
    "permanent": true
    },
    {
    "id": "Half-Sister",
    "desc": "This girl has one parent in common with you",
    "effect": "Sibling",
    "permanent": true,
    "client": true
    },
   {
    "id": "Alien",
    "desc": "This girl has come from a distant dimension with very different laws of physics, magic and society.",
    "mod": {"upkeep": 50},
    "mod_stats": {"magic": [-3, 1], "constitution": [-2, 2]},
    "max": {"magic": 20, "attack": 10, "defence": 10, "constitution": 15},
    "mod_skills": {"refinement": [-0.01, -0.06, 0.02], "service": [0, -0.03, -0.01]},
    "permanent": true,
    "defence_bonus": {"magic":[0, 50, 50], "status":[5, 50, 50]}
    }
]

=== DarkTl/PyTFall/game/content/db/traits_MC.json
[
    {
    "id": "Amazon Training",
    "desc": "Your mother watched over your training since childhood. As a result, your body is in a great condition.",
    "max": {"vitality": 25, "health": 25},
    "MC_only_trait": true
    },
    {
    "id": "Amazon Musculature",
    "desc": "You inherited your mother's strength. Melee weapons deal more damage than usual.",
    "delivery_multiplier": {"melee": 0.25},
    "MC_only_trait": true
    },
    {
    "id": "Yuri Expert",
    "desc": "You know a lot about lesbians from your Amazon mother. Lesbian characters will not reject you due to your gender, and your oral skill is pretty good.",
    "mod_skills": {"oral": [0, 0.1, 0.1]},
    "MC_only_trait": true
    },
    {
    "id": "Amazon Blood",
    "desc": "Your mother was a muscular woman with huge knockers. Fortunately, you have inherited only her muscles.",
    "max": {"attack": 25, "constitution": 15},
    "MC_only_trait": true
    },
    {
    "id": "Royal Blood",
    "desc": "Noble blood gives you certain perks.",
    "mod_skills": {"dancing": [0, 0.02, 0.02], "refinement": [0, 0.02, 0.02]},
    "max": {"charisma": 15, "intelligence": 15},
    "MC_only_trait": true
    },
    {
    "id": "Dragon Blood",
    "desc": "The dragon blood is too thin to influence the looks, but it still makes melee weapons a bit less effective.",
    "defence_multiplier": {"melee":0.2},
    "MC_only_trait": true
    },
    {
    "id": "Stone Dragon Scales",
    "desc": "Your body is covered with tiny flakes. They are almost inconspicuous, but upon impact they become solid as stone, softening the blow.",
    "el_defence": {"physical": 0.2, "earth": 0.3},
    "MC_only_trait": true
    },
    {
    "id": "Fire Dragon Scales",
    "desc": "Your body is covered with tiny flakes. They are almost inconspicuous, but at higher temperatures they actively absorb and dissipate heat, making fire and, to some extent, electricity ineffective.",
    "el_defence": {"fire": 0.6, "electricity": 0.1},
    "MC_only_trait": true
    },
    {
    "id": "Defiler Dragon Scales",
    "desc": "Your body is covered with tiny flakes. They are almost inconspicuous, but they can make certain parts of your skin scabrous, which helps during intimacy.",
    "mod_skills": {"vaginal": [0, 0, 0.1], "anal": [0, 0, 0.03], "sex": [0, 0, 0.02]},
    "MC_only_trait": true
    },
    {
    "id": "Knightly Stance",
    "desc": "All equipment penalties to agility are less than usual.",
    "MC_trait": true
    },
    {
    "id": "Sword Master",
    "desc": "All swords are a bit more powerful than usual.",
    "MC_trait": true
    },
    {
    "id": "Sister Lover",
    "desc": "Incest is extremely common in royal families, and you know a lot about it from your mother stories. Characters with Half-Sister trait will not reject you due to kinship and will have additional disposition bonus.",
    "MC_only_trait": true
    },
    {
    "id": "Drow Blood",
    "desc": "Your mother was an elf from the deep bowels of the earth. You have inherited her mobility and flexibility.",
    "max": {"agility": 25, "charisma": 15, "constitution": -25},
    "evasion_bonus": [3, 3, 1],
    "MC_only_trait": true
    },
    {
    "id": "Poison Master",
    "desc": "You know a lot about poisons from your mother. Poison are much less effective against you, and your poison attacks much are stronger.",
    "el_defence": {"poison": 0.65},
    "el_damage": {"poison": 0.65},
    "MC_trait": true
    },
    {
    "id": "Dagger Master",
    "desc": "All daggers are a bit more powerful than usual.",
    "MC_trait": true
    },
    {
    "id": "Forest Elf Blood",
    "desc": "You inherited your mother's affinity to the nature. Healing spells work better on you, while earth and wind deal less damage.",
    "max": {"charisma": 10, "constitution": -10, "agility": 5},
    "el_defence": {"healing": -0.25},
    "el_damage": {"earth": 0.1, "wind": 0.1},
    "MC_only_trait": true
    },
    {
    "id": "Bow Master",
    "desc": "All bows are a bit more powerful than usual.",
    "MC_trait": true
    },
    {
    "id": "Ranger",
    "desc": "You know a lot about surviving outside of the city from your parents. Your exploration skills are second to none.",
    "mod_skills": {"exploration": [0.3, 0.2, 0.3]},
    "MC_only_trait": true
    },
    {
    "id": "Elven Features",
    "desc": "Due to your ancestry, the certain part of your body is a bit thinner than you would like. That makes anal sex much easier, but you have to try harder in the other hole.",
    "mod_skills": {"vaginal": [-0.2, 0, -0.2], "anal": [0.2, 0, 0.2]},
    "MC_only_trait": true
    },
    {
    "id": "Fae Blood",
    "desc": "All Fae are naturally resistant to most forms of magic. Magic is not very effective against you, including healing spells.",
    "defence_multiplier": {"magic":0.2},
    "el_defence": {"healing": 0.25},
    "MC_only_trait": true
    },
    {
    "id": "Summer Eternality",
    "desc": "Your body inherited some of your mother's unchangeability. You body restores some health every day, but healing items are almost ineffective.",
    "effects": ["Eternality Regeneration"],
    "MC_only_trait": true
    }
    ]

=== DarkTl/PyTFall/game/content/db/traits_testing.json
[
    {
        "id": "Freak",
        "desc": "Freaky Dreaky.",
        "basetrait": true,
        "resist": [
            "fire",
            "poison"
        ],
        "el_absorbs": {
            "water": 1,
            "air": 0.5
        }
    },
    {
        "id": "Prostitute",
        "occupations": [
            "SIW"
        ],
        "desc": "Someone who will love you no matter who you are or what you look like.",
        "basetrait": true,
        "blocks": ["Virgin"],
        "mod": {
            "charisma": 60
        },
        "max": {
            "charisma": 30
        },
        "mod_skills": {
            "vaginal": [
                0.1,
                0.1,
                0.1
            ],
            "anal": [
                0.1,
                0.1,
                0.1
            ],
            "oral": [
                0.1,
                0.1,
                0.1
            ]
        },
        "type": "sex",
        "init_lvlmax": {
            "charisma": 30
        },
        "init_max": {
            "charisma": 30
        },
        "init_mod": {
            "charisma": 20
        },
        "init_skills": {
            "vaginal": [
                33,
                100
            ],
            "anal": [
                33,
                100
            ],
            "oral": [
                33,
                100
            ]
        },
        "leveling_stats": {
            "charisma": [
                0,
                1
            ]
        }
    },
    {
        "id": "Stripper",
        "occupations": [
            "SIW"
        ],
        "desc": "Stripper.",
        "basetrait": true
    },
    {
        "id": "Service",
        "occupations": [
            "Server"
        ],
        "desc": "Service.",
        "basetrait": true
    },
    {
        "id": "Mage",
        "occupations": [
            "Warrior"
        ],
        "desc": "Some simple desc of a mage.",
        "basetrait": true,
        "mod": {
            "magic": 100
        },
        "max": {
            "magic": 50
        },
        "mod_skills": {},
        "type": "combat",
        "init_lvlmax": {
            "magic": 100,
            "mp": 100
        },
        "init_max": {
            "magic": 100,
            "mp": 100
        },
        "init_mod": {
            "magic": 50
        },
        "init_skills": {},
        "leveling_stats": {
            "attack": [
                -2,
                -1
            ],
            "defence": [
                -2,
                -1
            ],
            "magic": [
                0,
                1
            ],
            "mp": [
                0,
                2
            ]
        }
    },
    {
        "id": "Warrior",
        "occupations": [
            "Warrior"
        ],
        "desc": "Some simple desc of a grunt.",
        "basetrait": true,
        "mod": {
            "attack": 100,
            "defence": 100
        },
        "max": {
            "attack": 50,
            "defence": 50
        },
        "mod_skills": {},
        "type": "combat",
        "init_lvlmax": {
            "attack": 100,
            "defence": 50,
            "health": 100
        },
        "init_max": {
            "attack": 100,
            "defence": 50,
            "health": 100
        },
        "init_mod": {
            "attack": 50,
            "defence": 25
        },
        "init_skills": {},
        "leveling_stats": {
            "attack": [
                0,
                2
            ],
            "defence": [
                0,
                1
            ],
            "health": [
                0,
                1
            ],
            "magic": [
                -2,
                -1
            ],
            "mp": [
                -2,
                -1
            ]
        }
    }
]
